In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19, 20])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19 20]
1
(19,)
19
int64


In [10]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(0, 16, size=(4, 5))
print("Array:")
print(arr)
print(arr.itemsize, "bytes")
print(arr.nbytes, "bytes")

Array:
[[ 6  3 12 14 10]
 [ 7 12  4  6  9]
 [ 2  6 10 10  7]
 [ 4  3  7  7  2]]
4 bytes
80 bytes


In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array:")
print(arr)
print(arr[:2, :2])
print(arr[:, ::2])
print(arr[:, ::-1])

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [13]:
import numpy as np
arr = np.arange(1, 16)
print("Array:")
print(arr)
parts = np.split(arr, 3)

print(parts[0])

print(parts[1])

print(parts[2])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
