In [20]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6


In [39]:
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[3:9:2])
print(arr[::-1])
print(arr[1:2:3])
arr[2]=10
print(arr)

[5 8 9 5 0 0 1 7 6 9]
5
6
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]
[8]
[ 5  8 10  5  0  0  1  7  6  9]
